language: python
python:
  - "3.6"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

install:
  - pip install -r requirements.txt

script:
  - python3 ./images.py
